##########################开发环境##########################################
spring: 
  #数据库配置
  datasource:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://192.168.100.103:5432/postgres
      username: postgres
      password: postgres
      druid:
        #初始化连接大小
        initial-size: 1
        #最小空闲连接数
        min-idle: 5
        #最大连接数
        max-active: 60
        #查询超时时间
        query-timeout: 6000
        #事务查询超时时间
        transaction-query-timeout: 6000
        #关闭空闲连接超时时间
        remove-abandoned-timeout: 1800
        filters: stat,config